version: '3.1'
services:
  
  backend:
    build: ./backend
    command: npm run start
    volumes:
      - ./backend:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy

    environment:
      MONGO_DB_URL: ${MONGO_DB_URL}
      MONGO_DB_USER: ${MONGO_DB_USER}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
  
  frontend:
    build: ./frontend
    command: npm run start
    volumes:
      - ./frontend:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      PORT: 3001

  mongodb:
    image: mongo:5.0.9
    restart: always
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example